const mock = [
  { ticker: 'AAPL', price: 150 },
  { ticker: 'AMZN', price: 230 },
  { ticker: 'NTFLX', price: 123 },
  { ticker: 'GOGLE', price: 54 },
  { ticker: 'COCA', price: 145 },
  { ticker: 'PEPSI', price: 10 },
  { ticker: 'TESLA', price: 340 },
  { ticker: 'FORD', price: 123 },
  { ticker: 'NBD', price: 123 },
  { ticker: 'WSZ', price: 15 },
  { ticker: 'SDRF', price: 75 },
  { ticker: 'AAPL', price: 150 },
  { ticker: 'AMZN', price: 230 },
  { ticker: 'NTFLX', price: 123 },
  { ticker: 'GOGLE', price: 54 },
  { ticker: 'AAPL', price: 150 },
  { ticker: 'AMZN', price: 230 },
  { ticker: 'NTFLX', price: 123 },
  { ticker: 'GOGLE', price: 54 },
  { ticker: 'COCA', price: 145 },
  { ticker: 'PEPSI', price: 10 },
  { ticker: 'TESLA', price: 340 },
  { ticker: 'FORD', price: 123 },
  { ticker: 'NBD', price: 123 },
  { ticker: 'WSZ', price: 15 },
  { ticker: 'SDRF', price: 75 },
  { ticker: 'AAPL', price: 150 },
  { ticker: 'AMZN', price: 230 },
  { ticker: 'NTFLX', price: 123 },
];

export default mock;
